#!/usr/bin/env python2
# -*- coding: utf-8 -*-

import numpy as np
import pandas as pd

raw_data = 'gse121411_tpmmatrix1.txt'
data = np.genfromtxt(raw_data, delimiter='\t')
df = pd.DataFrame(data)

index_data = 'gse121411_expressionmatrix1.txt' 
df.index = np.genfromtxt(index_data, delimiter='\t', skip_header=3, usecols= [1])

column_data = 'gse121411_expressionmatrix1.txt'
row_index = 2  # Choose the desired row index containing the column names
column_names = np.genfromtxt(column_data, delimiter='\t')
selected_column_names = column_names[row_index,2:]

series_data = np.genfromtxt('gse121411_seriesmatrix.txt', delimiter='\t', skip_header=35, dtype=str)

# Sample title 가져오기
sample_title = series_data[0, 1:]
sample_fromcolumn, sample_description = np.char.split(sample_title, " ")

sample_description = np.array(sample_description)
for i in range(len(selected_column_names)):
    for j in range(len(sample_fromcolumn)):
        if selected_column_names[i] == sample_fromcolumn[j]:
            selected_column_names[i] = sample_description[j]

df.columns = selected_column_names

df.to_csv('tpmvalue_withindexandcolumn.csv', index=True, header=True)
